# Generated by Django 5.2.9 on 2025-12-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
